version: '3.8'

services:
  fluent-bit:
    image: registry.eniac-tech.com/fluent/fluent-bit:3.2.10
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./functions.lua:/fluent-bit/etc/functions.lua
    networks:
      - logging

  log-generator:
    build: .
    depends_on:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.{{.Name}}"
    networks:
      - logging

networks:
  logging:
    driver: bridge